version: '3.8'

services:
  app:
    build: .
    container_name: souvenir-gallery-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod

  db:
    image: postgres:15
    container_name: souvenir-db
    environment:
      POSTGRES_DB: souvenir-db
      POSTGRES_USER: liubakapower
      POSTGRES_PASSWORD: !@$%@!As123
    ports:
      - "8854:8854"
    volumes:
      - postgres_data:/var/lib/postgresql/data
