FROM node:18 AS frontend-build

WORKDIR /frontend

COPY ./souvenir-gallery/package.json ./souvenir-gallery/package-lock.json ./

RUN npm install

COPY ./souvenir-gallery .

RUN npm run build

FROM maven:3.8.4-jdk-11 as builder

COPY ./souvenir-be /app

WORKDIR /app

RUN mvn clean package

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080


